version: "3.7"

services:
  hello-world:
    container_name: hello-world
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:4.12.1"
    entrypoint: "cypress run --config-file ./cypress-docker.json"
    depends_on:
      - hello-world
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://172.19.0.2:3000
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
